import type { Question } from './types';

export const questions: Question[] = [
  {
    id: 'name',
    type: 'text',
    keyEn: 'Your name',
    keyNl: 'Uw naam',
    required: true,
  },
  {
    id: 'company',
    type: 'text',
    keyEn: 'Company / Organization',
    keyNl: 'Bedrijf / Organisatie',
    required: true,
  },
  {
    id: 'email',
    type: 'email',
    keyEn: 'Email address',
    keyNl: 'E-mailadres',
    required: true,
  },
  {
    id: 'phone',
    type: 'tel',
    keyEn: 'Phone number (optional)',
    keyNl: 'Telefoonnummer (optioneel)',
    required: false,
  },
  {
    id: 'hear_about',
    type: 'select',
    keyEn: 'How did you hear about GIANT Agency?',
    keyNl: 'Hoe heeft u over GIANT Agency gehoord?',
    options: [
      { en: 'Social media (Instagram / LinkedIn)', nl: 'Sociale media (Instagram / LinkedIn)' },
      { en: 'Search engine (Google)', nl: 'Zoekmachine (Google)' },
      { en: 'Referral from a colleague', nl: 'Aanbeveling van een collega' },
      { en: 'Billboard / outdoor advertisement', nl: 'Billboard / buitenreclame' },
      { en: 'Event or conference', nl: 'Evenement of conferentie' },
      { en: 'Other', nl: 'Anders' },
    ],
    required: true,
  },
  {
    id: 'service_interest',
    type: 'checkbox',
    keyEn: 'Which services are you interested in?',
    keyNl: 'In welke diensten bent u geïnteresseerd?',
    options: [
      { en: 'Billboard design & production', nl: 'Billboard ontwerp & productie' },
      { en: 'OOH / DOOH campaign strategy', nl: 'OOH / DOOH campagne strategie' },
      { en: 'Brand activation', nl: 'Merkactivering' },
      { en: 'Creative consulting', nl: 'Creatief advies' },
      { en: 'Campaign production & execution', nl: 'Campagneproductie & uitvoering' },
      { en: 'Other', nl: 'Anders' },
    ],
    required: true,
  },
  {
    id: 'project_description',
    type: 'textarea',
    keyEn: 'Tell us about your project or campaign idea',
    keyNl: 'Vertel ons over uw project of campagne-idee',
    required: true,
  },
  {
    id: 'budget',
    type: 'radio',
    keyEn: 'What is your estimated budget?',
    keyNl: 'Wat is uw geschatte budget?',
    options: [
      { en: 'Under €5,000', nl: 'Onder €5.000' },
      { en: '€5,000 – €15,000', nl: '€5.000 – €15.000' },
      { en: '€15,000 – €50,000', nl: '€15.000 – €50.000' },
      { en: '€50,000+', nl: '€50.000+' },
      { en: 'Not sure yet / Prefer not to say', nl: 'Nog niet zeker / Zeg ik liever niet' },
    ],
    required: true,
  },
  {
    id: 'timeline',
    type: 'radio',
    keyEn: 'What is your timeline?',
    keyNl: "Wat is uw tijdlijn?",
    options: [
      { en: 'ASAP — within 2 weeks', nl: 'ASAP — binnen 2 weken' },
      { en: 'Within 1 month', nl: 'Binnen 1 maand' },
      { en: 'Within 3 months', nl: 'Binnen 3 maanden' },
      { en: 'Just exploring for now', nl: 'Nu alleen aan het verkennen' },
    ],
    required: true,
  },
  {
    id: 'newsletter',
    type: 'radio',
    keyEn: 'Would you like to receive updates and inspiration from GIANT?',
    keyNl: 'Wilt u updates en inspiratie ontvangen van GIANT?',
    options: [
      { en: 'Yes, keep me inspired!', nl: 'Ja, houd me geïnspireerd!' },
      { en: 'No, thanks', nl: 'Nee, bedankt' },
    ],
    required: true,
  },
  {
    id: 'notes',
    type: 'textarea',
    keyEn: 'Anything else you\'d like to share? (optional)',
    keyNl: 'Iets anders dat u wilt delen? (optioneel)',
    required: false,
  },
];
